openid/authzen

authorization-api-1_0.md
=> Alternative text for API Authorization section

interop/authzen-todo-backend/src/directory.ts, interop/authzen-todo-backend/src/interfaces.d.ts, interop/authzen-todo-backend/src/server.ts
Changes to the `authzen-todo-backend` sub-repo:
* added `roles` attribute to the json in `directory.ts`
* changed the `"key"` key to `"id"`, to match up with what's in the interop payload document
=> added missing roles attributes to directory.ts and minor cleanup

api/authorization-api-1_0.md
This PR cleans up a few discrepancies / inconsistencies between the interop scenario and the existing draft:
1. consistent treatment of case. all JSON keys are consistently lowercased, to match the examples, and match the interop payloads.
2. renamed the sections called "Access Evaluation API Request/Response" to "Access Evaluation**s** Request/Response". these sections describe the boxcarred API. 
3. added corresponding sections called "Access Evaluation API Request/Response" which describes the NON boxcarred version that is used in the interop scenario. All payloads are now consistent with the [payloads spec](https://authzen-interop.net/docs/scenarios/todo). 
4. cleaned up JSON formatting - all indentation now uses 2 spaces, as is standard. Most of the spec was consistent with this, but …
=> updated spec to include a separate single-evaluation API description, and other cleanup

api/authorization-api-1_0.md
- Added "context" to the response descriptions for the /evaluation and /evaluations calls
- Fit the current "reason object" specification within the "context" description
- Made the changes required to fix the CI failures for publishing the spec
=> updated eval calls to include "context" in response, and fixed CI

interop/authzen-todo-backend/scripts/test.sh
In `interop/authzen-todo-backend`, the `scripts/test.sh` bash script did not use the `AUTHZEN_PDP_API_KEY` environment variable. This PR fixes it.
=> updated test script to use AUTHZEN_PDP_API_KEY

api/authorization-api-1_0-original.md, api/authorization-api-1_0.md
* removed Evaluations and Search APIs
* cleaned up all JSON
* added subject IDs as per RFC9493 (subsuming @tulshi's earlier PR)
* added required `type` field for subjects and objects as discussed
* added required `name` field for actions as discussed
* cleanly factored HTTPS binding into the transports section
* added example annotations for every JSON example
* fixed all the bullets that weren't rendering correctly
* grammar and typos
=> refactor API spec to remove search and boxcarred apis and cleanup

api/authorization-api-1_0.md
This addresses issue https://github.com/openid/authzen/issues/86
=> clarify https error codes vs deny decisions

api/authorization-api-1_0.md
This PR captures the AuthZEN discussion from June 25 2024, where the WG decided to make Resource ID mandatory.
=> make resource id mandatory

interop/authzen-interop-website/docs/results/3edges.md, interop/authzen-interop-website/docs/results/RockSolidKnowledge.md, interop/authzen-interop-website/docs/results/aserto.md, interop/authzen-interop-website/docs/results/authzforce.md, interop/authzen-interop-website/docs/results/axiomatics.md, interop/authzen-interop-website/docs/results/cerbos.md, interop/authzen-interop-website/docs/results/hexa.md, interop/authzen-interop-website/docs/results/kogito.md, interop/authzen-interop-website/docs/results/opa.md, interop/authzen-interop-website/docs/results/permit.md, interop/authzen-interop-website/docs/results/plainid.md, interop/authzen-interop-website/docs/results/sgnl.md, interop/authzen-interop-website/docs/results/topaz.md, interop/authzen-interop-website/docs/scenarios/todo.md, interop/authzen-todo-backend/test/runner.ts
* improve test runner markdown generator to create something much more viewable in docusaurus, using <table> tags
* re-generate all 13 results pages
=> facelift for table/markdown interop results and generation

interop/authzen-todo-application/.env, interop/authzen-todo-application/src/App.tsx, interop/authzen-todo-application/src/LoginWrapper.tsx, interop/authzen-todo-application/src/components/Todo.tsx, interop/authzen-todo-application/src/index.css, interop/authzen-todo-application/src/interfaces.ts, interop/authzen-todo-application/src/todoService.tsx, interop/authzen-todo-backend/src/auth.ts, interop/authzen-todo-backend/src/index.ts, interop/authzen-todo-backend/src/interfaces.d.ts, interop/authzen-todo-backend/src/pdps.json, interop/authzen-todo-backend/src/server.ts, interop/authzen-todo-backend/test/decisions-1.0-implementers-draft.json, interop/authzen-todo-backend/test/decisions-1.0-preview.json, interop/authzen-todo-backend/test/decisions-1.1-preview.json, interop/authzen-todo-backend/test/runner.ts, interop/authzen-todo-backend/tsconfig.json
Changes required to make interop scenario work with the 1.0 implementer's draft.
Front-end:
* added spec version selector in front-end
* prepped for 1.1 by adding a "CannotUpdate" field to each Todo returned, which shows a disabled update button
* send specversion and pdp with each request to the backend
Back-end:
* pdps.json now organizes implementations based on spec version - "1.0-preview", "1.0-implementers-draft", and "1.1-preview"
* the "1.1-preview" will make an `evaluations` call to a compliant back-end to determine whether a user can update each of the todos
* the todo list is enhanced with the CannotUpdate field if the user doesn't have permission to update the todo
The App is compatible with all three types of implementations - existing, 1.0-implementers-draft compliant, and …
=> initial commit for implementers draft changes

interop/authzen-todo-backend/test/decisions-1.0-implementers-draft.json, interop/authzen-todo-backend/test/decisions-1.0-preview.json, interop/authzen-todo-backend/test/decisions-1.1-preview.json, interop/authzen-todo-backend/test/decisions.json
In the current decision*.json files, the same todo ID is used when checking if users `can_update_todo` when a specific user is the owner. This implies that the same Todo item is owned by different users, which is probably not intended.
```
{
"request": {
"subject": {
"type": "user",
"id": "CiRmZDQ2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
},
"action": {
"name": "can_update_todo"
},
"resource": {
"type": "todo",
"id": "7240d0db-8ff0-41ec-98b2-34a096273b9f",
"properties": {
"ownerID": "jerry@the-smiths.com"
}
}
},
"expected": false
},
```
This PR updates the decision*.json files to use unique todo:id identifiers for todo items owned by different users:
- morty@the-citadel.com - 7240d0db-8ff0-41ec-98b2-34a096273b91
- rick@the-citadel.com -  7240d0db-8ff0-41ec-98b2-34a096273b92
- …
=> Added unique resource IDs per owner

api/authorization-api-1_0_02.md
This PR contains two substantive changes to the AuthZEN 1.0 spec:
* Removes the default actions ("can_read", "can_write", etc), as a result of many pieces of feedback that this is confusing and doesn't add anything to the spec.
* Adds the `options.evaluations_semantic` section to specify the execution semantics of the `evaluations` call, as agreed in the December 17 2024 AuthZEN call.
=> removed default actions and added evaluations semantics

api/schemas/evaluation-request.schema.json, api/schemas/evaluation-response.schema.json
Creating the [json-schema 2020-12](https://json-schema.org/draft/2020-12/json-schema-core) schema for the `access evaluation request` and `access evaluation response` from the schema define at [Authzen - Authorization API 1.1 - draft 01](https//openid.github.io/authzen/authorization-api-1_1_01)
- https://github.com/openid/authzen/issues/109
1. We should consider some kind of testing to ensure that schema are compliant, as of today I'm manually validating via https://www.jsonschemavalidator.net/ and some basic example
a. ensure minimum schema
b. ensure the additional properties are allowed when allowed
2. The field [$id](https://www.learnjsonschema.com/2020-12/core/id/) should be replace with a more permanent id (eg: IANA registration ?)
3. We can reuse the schema to create an valid [OAS …
=> feat: JSON schema for Access Evaluation Request/Response

interop/authzen-todo-backend/src/auth.ts
Fixes https://github.com/openid/authzen/issues/190
=> Use proper ID for todo Item in can_update_todo and can_delete_todo

api/authorization-api-1_0.md, interop/authzen-interop-website/docs/scenarios/todo-1.0-id/index.md, interop/authzen-interop-website/docs/scenarios/todo-1.1/index.md, interop/authzen-interop-website/docs/scenarios/todo/index.md, interop/authzen-todo-backend/README.md
* Update spec URLs in interop website to reflect stable spec URLs
* Update README in interop backend to reflect correct API_KEY variable format
* Update API document name to the non-revisioned name
=> updated spec URLs and readme/docs

interop/authzen-todo-backend/src/index.ts, interop/authzen-todo-backend/src/server.ts
This helps gateways dynamically retrieve the set of PDPs that are compliant with the gateway interop spec.
=> add /gatewaypdps endpoint to backend

interop/authzen-api-gateways/aws-api-gateway/authzen.mjs, interop/authzen-api-gateways/envoy-gateway/authzen-external-authorizer/authzen.go, interop/authzen-api-gateways/kong-gateway/kong/plugins/authzen/access.lua, interop/authzen-api-gateways/test-harness/test/decisions.json, interop/authzen-api-gateways/tyk-gateway/plugins/authzen.go, interop/authzen-interop-website/docs/scenarios/api-gateway/index.md, interop/authzen-interop-website/docs/scenarios/api-gateway/results/RockSolidKnowledge.md, interop/authzen-interop-website/docs/scenarios/api-gateway/results/aserto.md, interop/authzen-interop-website/docs/scenarios/api-gateway/results/axiomatics.md, interop/authzen-interop-website/docs/scenarios/api-gateway/results/cerbos.md, interop/authzen-interop-website/docs/scenarios/api-gateway/results/plainid.md
This PR changes a number of artifacts to use "identity" instead of "user" for `subject.type` 
This is based on feedback that the strings we use are PIDs from JWTs, and do not resemble what a "user" id would look like (typically an email).
=> update gateway scenario to use "identity" instead of "user" 

interop/authzen-api-gateways/envoy-gateway/authzen-external-authorizer/authzen.go, interop/authzen-api-gateways/envoy-gateway/authzen-external-authorizer/main.go
Read keys from env and include in call to PDP
The env variable on the deployment can be constructed via:
```
AUTHZEN_PDP_AUTH_CONFIG=$(echo '{"topaz":{"token":"topaz-token"}}' | base64)
```
=> envoy: Support PDP AuthN

interop/authzen-interop-website/docs/scenarios/todo-1.1/index.md
I'm developing the **PDP evaluation endpoint** for **WSO2 Identity Server**, using the specification while also validating it against **Interop Scenarios**.
I noticed an inconsistency in the **[PUT todo section](https://authzen-interop.net/docs/scenarios/todo-1.1/#put-todosid)**—the descriptions do not align with the corresponding request and response payloads.
For example, the request payload description states:
> *The `resource.properties` contains an attribute called `ownerID`, which holds the owner's ID (as defined in the "Attributes" section above, where it is the owner's email address).*
However, the actual payload **does not contain a `properties` section**, making the description misleading.
To ensure accuracy and consistency, I am submitting this **PR to correct the …
=> Fix Misalignment Between Request Payload and Description in PUT Todo Section

interop/authzen-api-gateways/aws-api-gateway/openapi/todo-openapi.json
This PR addresses the issue of the missing `userId` path parameter in the `/users/{userId}` endpoint.
Changes:
- Defined userId as a required path parameter in the get operation.
- Set userId type to string to align with the UserObject schema.
=> Fix missing userId path parameter in /users/{userId} endpoint

api/authorization-api-1_0.md
As discuss during the WG meeting on April 8th, here is a first proposal for the PDP Metdata Discovery feature for comments.
It is based on [RFC8414](https://datatracker.ietf.org/doc/html/rfc8414) and [I.D-ietf-oauth-resource-metadata](https://datatracker.ietf.org/doc/draft-ietf-oauth-resource-metadata/).
=> PDP Metdata Discovery feature

README.md, api/authorization-api-1_0.md
This PR fix minor typo in  ReadMe and the Spec, that I found when implementing search API in WSO2 Identity Server.
- **Typo Fix**: Corrected the word `"conrtols"` to `"controls"` in the *Evaluations options* section.
- **JSON Fixes**: Fixed several JSON examples by:
- Quoting unquoted keys such as `decision`
- Removing trailing commas from objects (e.g., `"id": "123",` → `"id": "123"`)
These changes help improve readability and prevent JSON parsing issues.
@ogazitt please approve if its applicable
=> Fix minor typo

api/authorization-api-1_0.md, api/schemas/evaluation-request.schema.json
This addresses https://github.com/openid/authzen/issues/42 (which I think is reasonable feedback). The term "machine identity" is more prevalent than "robotic identity".
=> changed "robotic" to "machine" to describe machine identities

api/authorization-api-1_0.md
This PR fixes some broken markdown that we accumulated as a result of recent PRs.
The kramdown / xml2rfc process is now once again producing error/warning-free builds.
=> updated markdown to fix xml2rfc flagged issues

interop/authzen-todo-backend/.dockerignore
This allows a local `yarn start` to continue to work, since the `./db` directory is part of source control.
The `.dockerignore` will ensure the directory doesn't exist, but will then require a volume mount for the sqllite volume
=> create a dummy ./db directory and ignore it in the docker builds

api/authorization-api-1_0.md
This PR adds several changes to prevent the confusion that lead to issue https://github.com/openid/authzen/issues/352 being raised. 
It: 
- Defines that the endpoints in the HTTP transport binding should correspond to those defined in the PDP metadata.
- Fixes capitalization of Content-Type and added it in the example.
- Adds the action endpoint to the IANA registry for PDP metadata (incl. small typo)
=> Defined relation between paths in HTTP transport binding and PDP metadata + small fixes

api/authorization-api-1_0.md
1. Corrected the old references to the .well-known spec 5785 -> 8615
2. Added an example of a metadata URL for a multi-tenant PDP
3. Added text to make providing metadata recommended
Note: I did not add any text recommending using the default names for the APIs as I didn't find any examples or call outs of those endpoint names in the spec. We may need an additional PR to address that aspect per issue #358.
This PR addresses issues #358 and #359.
=> Addressing issues #358 and #359 policy metadata
