openid/authzen

interop/authzen-todo-backend/scripts/test.sh
interop/authzen-todo-backend/src/auth.ts

`/access/v1/evaluations` -> `/access/v1/evaluation`

updated todo backend evaluation api to conform to new spec

---

interop/authzen-interop-website/docs/results/axiomatics.md

Output of running the test script on the Axiomatics PDP hosted at https://alfa.pdp.guide

Added the results for the Axiomatics PDP

---

interop/authzen-interop-website/docs/results/RockSolidKnowledge.md
interop/authzen-todo-backend/src/pdps.json

Implementation of AuthZen PDP wire protocol for Rock Solid Knowledge Enforcer PDP

Added RSK PDP to interop tests

---

api/authorization-api-1_0.md

Removed a comment and fixed some syntax issues.

Updates to the security considerations

---

interop/authzen-interop-website/docs/scenarios/todo.md
interop/authzen-todo-backend/src/auth.ts
interop/authzen-todo-backend/test/decisions.json

Updates:
* interop payload spec updated to reflect changes in https://hackmd.io/gNZBRoTfRgWh_PNM0y2wDA?both
* authzen-todo-backend authorization middleware updated to generate new payloads
* decisions.json file updated to use new payload structure

updated interop to be 1.0 compliant

---

api/authorization-api-1_0_01.md

Moved Document History to the end of the file

Update authorization-api-1_0_01.md to move History section

---

.github/workflows/jekyll-gh-pages.yml
api/authorization-api-1_1_01.md

* created 1_1_01 revision
* added CI for it and removed CI for older revisions
* brought up 1_1_01 in alignment with 1_0_01
* changed `evaluations` map to an array

1.1 evaluations to array

---

interop/authzen-interop-website/docs/scenarios/todo-1.0-id/results/axiomatics.md

Updated the results from Axiomatics for the 1.0 implementer's draft to be in the same format as all the other ones and integrate with the website.

Updated md format to be in the format expected by the interop website

---

README.md

This PR adds more details on the content of the repo.
It also includes instructions on how to build the spec from markdown into HTML output.

added build instructions to README

---

interop/authzen-todo-backend/src/auth.ts

This PR fixes a build break introduced by https://github.com/openid/authzen/pull/191

fix build break in https://github.com/openid/authzen/pull/191

---

api/authorization-api-1_0.md

This PR adds the Subject Search and Resource Search APIs as proposed in https://hackmd.io/c8aAiipoRpGtMIrM3bvDTg?view and discussed on the AuthZEN call on 2025-01-28.

Draft 03 - adds subject search and resource search APIs

---

interop/authzen-todo-backend/src/pdps.json

Add Kong and Zuplo to Gateway list

add kong and zuplo to gateway list

---

api/authorization-api-1_0.md

Added change serch to the authirization-api spec

Added Action Search

---

api/authorization-api-1_0.md

This commit:
* increments the draft number to 04
* fixes example 6.2.4 to address https://github.com/openid/authzen/issues/249

draft 04 initial commit

---

api/authorization-api-1_0.md

fix resource search URL inconsistency

---

api/authorization-api-1_0.md

This PR resolves a few open issues:
* #269 
* #270 
* #271 
* #272 
* #291

clarified search semantics

---

api/authorization-api-1_0.md

PLEASE DON'T MERGE
this is a PR for the PDP metadata endpoint and the discovery feature for discussions

Discovery feature PR for discussions

---

api/authorization-api-1_0.md

Just updating my contact info...

Update AlexB's contact info.

---

interop/authzen-api-gateways/envoy-gateway/envoy/envoy.yaml

Update envoy config to use new demo domain

---

interop/authzen-search-demo/Dockerfile

Was missed in the change from NPM

Migrate to yarn in Dockerfile

---

interop/authzen-interop-website/docs/scenarios/search/results/axiomatics.md

Search results for Axiomatics. I ran them locally FYI and haven't deployed to GCP yet. My URL will be the same as for the other demos (https://pdp.alfa.guide).

Added the Axiomatics search results

---

api/authorization-api-1_0.md

Adding a sender authentication failure section

Update authorization-api-1_0.md security section

---

api/authorization-api-1_0.md

Added recommended paths to endpoints and rewrote the section to be more normative regarding POST and Content-Type structure.

Added recommended paths to endpoints 

---

api/authorization-api-1_0.md

Updated the title to draft 05 and added Michiel Trimpe as a contributor.

Update Authorization API title and contributors

---

api/authorization-api-1_0.md

Edited for consistency regarding terminology and transport agnostic requirements.

Consistency edit
